version: '3'

services:
  gpt4free:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '1337:1337'
    environment:
      - PYTHONUNBUFFERED=1
      - GUNICORN_BIND=0.0.0.0:1337